#!/bin/bash
yum update -y
yum install -y httpd
amazon-linux-extras enable php7.4
yum clean metadata
yum install -y php php-common php-pear
yum install -y php-{cgi,curl,mbstring,gd,mysqlnd,gettext,json,xml,fpm,intl,zip}
systemctl start httpd
systemctl enable httpd
#Install mysql cli on Amazon Linux 2
sudo yum install mysql -y
# Connect to the database and populate the table
mysql -u admin -h <dbendpoint> -p"DBPassword" << 'EOF'
use labdata;
create table locations (city varchar(30), state varchar(30), zip int);
insert into locations (city,state,zip) values ('Knoxville','TN',37748);
insert into locations (city,state,zip) values ('Atlanta','GA',30135);
insert into locations (city,state,zip) values ('Freehold','NJ',07728);
EOF
# Create the PHP home page
cat << 'EOF' > /var/www/html/index.php
<!DOCTYPE html>
<html>
<body>
    <center>
    <?php
    $host_name = file_get_contents("http://169.254.169.254/latest/meta-data/hostname");
    $public_ip = file_get_contents("http://169.254.169.254/latest/meta-data/public-ipv4");
    $instance_id = file_get_contents("http://169.254.169.254/latest/meta-data/instance-id");
    $az = file_get_contents("http://169.254.169.254/latest/meta-data/placement/availability-zone");
    ?>
    <h1>Wecome to: <?php echo $host_name ?></h1>
    <h2>Public IP: <?php echo $public_ip ?></h2>
    <h2>Instance ID: <?php echo $instance_id ?></h2>
    <h2>Availability Zone: <?php echo $az ?></h2>
    </center>
</body>
</html>
EOF

cat << 'EOF' > /var/www/html/locations.php
<html>
<head>
    <title>Locations</title>
</head>

<body>
<?php
$host_name = file_get_contents("http://169.254.169.254/latest/meta-data/hostname");
$public_ip = file_get_contents("http://169.254.169.254/latest/meta-data/public-ipv4");
$instance_id = file_get_contents("http://169.254.169.254/latest/meta-data/instance-id");
$az = file_get_contents("http://169.254.169.254/latest/meta-data/placement/availability-zone");
?>
<h2>Wecome to: <?php echo $host_name ?></h1>
<h3>Public IP: <?php echo $public_ip ?></h2>
<h3>Instance ID: <?php echo $instance_id ?></h2>
<h3>Availability Zone: <?php echo $az ?></h2>
<hr>

<?php

$databaseHost = '<dbendpoint>';
$databaseName = 'labdata';
$databaseUsername = 'admin';
$databasePassword = 'DBPassword';

$mysqli = mysqli_connect($databaseHost, $databaseUsername, $databasePassword, $databaseName);

// Check connection
if (!$mysqli) die("Database Connection failed: " . mysqli_connect_error());
echo "Connected successfully to: " . $databaseName;
echo "</br></br>";

//Extract form data
if(isset($_POST['city'])) $city = $_POST['city'];
if(isset($_POST['state'])) $state = $_POST['state'];
if(isset($_POST['zip'])) $zip = $_POST['zip'];
$sql = "INSERT INTO locations (city, state, zip)
        VALUES ('$city', '$state', '$zip')";
if ($city) {
    if (mysqli_query($mysqli, $sql)) {
    echo "New record created successfully";
    } else {
    echo "Error: " . $sql . "<br>" . mysqli_error($mysqli);
    }
} else {
    echo "Ready to add new data...";
}

//fetching data
$result = mysqli_query($mysqli, "SELECT * FROM locations");
?>
    <h2>Enter City State and Zip to add a new record.</h2>
    <form name="input" action="locations.php" method="post" class="form-horizontal">
        <label for="City">City</label> <input type="text" name="city">
        <label for="State">State</label> <input type="text" name="state">
        <label for="Zip">Zip</label> <input type="text" name="zip">
        <input type="submit" value="Add"/>
    </form>
    </br>
    <h1>Locations</h1>
    </br>
    <table width='80%' border=0>
        <tr bgcolor='#CCCCCC'>
            <td>City</td> <td>State</td> <td>Zip</td>
        </tr>
        <?php
        while($res = mysqli_fetch_array($result)) {
            echo "<tr>";
            echo "<td>".$res['city']."</td>";
            echo "<td>".$res['state']."</td>";
            echo "<td>".$res['zip']."</td>";
        }
        ?>
    </table>
</body>
<script>
if (window.history.replaceState) {window.history.replaceState( null, null, window.location.href );}
</script>
</html>
EOF
